### ISSUE TITLE
RAW Query fails when server and DB are on differents IPs

### ISSUE THREAD

**Issue by A-Corregidor** [loopbackio/loopback-next#8308] opened 2022-02-17 11:08 UTC
### Describe the bug

LB4 app working as expected: several models, controllers, repositories, connected to a MySQL datasource.
- Development server: server and DB machine are the same 
- Production server (deployed on AWS): server and DB machine are different (both are connected through local network)

If we query at model X through LB4 ORM (modelXRepository.find()), it works as expected.
If we query at model X through LB4 execute method (modelXRepository.execute(thisIsAValidQuery)), we've found two cases:
- Development server: Works as expected
- Production server (deployed on AWS): The query fails because the IP to where the query is sent is the Node machine, not the DB 

Examples (using DB config specified on Additional Information):
- Develop / Production, LB4 ORM query: it works as expected on both cases (returns query's result)
- Develop, RAW query: works as expected (returns query's result), as it's sent to "devUsername@10.0.0.1:3306" (which is equivalent to localhost)
- Production, RAW query: fails as it's sent to "prodUsername@10.0.0.5:3306" (instead of "prodUsername@prodIp" as specified on datasourceConfig file). Error message: "Error: ER_TABLEACCESS_DENIED_ERROR: SELECT command denied to user 'prodUsername'@'10.0.0.5' for table 'CashTransaction'" _<- IP Should be prodIP, not server machine's IP_

We're not really sure if this is a LB4 problem or a MySQLConnector problem.
We'd to use execute() to be able to do an INNER JOIN, as (as far as we know), LB4 doesn't support it (we need to filter over related models)

### Additional information

DB config example (some properties are omitted, as connector, name, url, etc)

Development datasource config (let's suppose this machine has the IP 10.0.0.1):
```
{
  "host": "localhost",
  "port": 3306,
  "user": "devUsername",
  "password": "devPasword",
  "database": "devDb"
}
```

Production datasource config (let's suppose this machine has the IP 10.0.0.5):
```
{
  "host": "prodIp",
  "port": 3306,
  "user": "prodUsername",
  "password": "prodPasword",
  "database": "prodDb"
}
```

### Reproduction

Hard to integrate on sandbox

**Comment by achrinza** [comment] 2022-02-17 13:51
Duplicate of https://github.com/loopbackio/loopback-connector-mysql/issues/462

**Closed by achrinza** 2022-02-17 13:51 UTC
Labels: bug
