### ISSUE TITLE
Circular Dependency Between Model A-B When Setting Relations

### ISSUE THREAD

**Issue by A-Corregidor** [loopbackio/loopback-next#9041] opened 2022-10-27 13:01 UTC
### Describe the bug

(A) Model:
{
	@property({
		type: 'string',
		id: true,
		defaultFn: 'uuid',
	})
	id: string;

	@property({
		type: 'string',
		required: true,
		index: true,
	})
	name: string;

	@hasMany(() => ModelB, { keyTo: 'modelAId' })
	ModelBs: ModelB[];
}

-----------------------------------------------------------------

(B) Model:
{
	@property({
		type: 'string',
		id: true,
		defaultFn: 'uuid',
	})
	id: string;

	@property({
		type: 'string',
		required: true,
		index: true,
	})
	name: string;

	@belongsTo(() => ModelA)
	modelAId?: string;
}

-----------------------------------------------------------------

(A) Repository:
{
        export class ModelARepository extends DefaultCrudRepository<ModelA, typeof ModelA.prototype.id, ModelARelation> {
	public readonly modelBs: HasManyRepositoryFactory<ModelB, typeof ModelA.prototype.id>;

	constructor(
		@inject('datasources.mySqlDb') dataSource: MySqlDbDataSource,
		@repository.getter('ModelBRepository')	modelBRepositoryGetter: Getter<ModelBRepository>,
	) {
		super(VtcLicense, dataSource);
		this.modelBs = this.createHasManyRepositoryFactoryFor(
			'modelBs',
	 	modelBRepositoryGetter,
		);
		this.registerInclusionResolver('modelBs', this.modelBs.inclusionResolver);
	}
}

-----------------------------------------------------------------

(B) Repository:
{
        export class ModelBRepository extends DefaultCrudRepository<ModelB, typeof ModelB.prototype.id, ModelBRelation> {
	public readonly modelA: BelongsToAccessor<ModelA, typeof ModelB.prototype.id>;

	constructor(
		@inject('datasources.mySqlDb') dataSource: MySqlDbDataSource,
		@repository.getter('ModelARepository')	protected modelARepositoryGetter: Getter<ModelARepository>,
	) {
		super(VtcLicense, dataSource);
		this.modelA = this.createBelongsToAccessorFor('modelA', modelARepositoryGetter);
		this.registerInclusionResolver('modelA', this.modelA.inclusionResolver);
	}
}

-----------------------------------------------------------------

ERROR -> Error: Circular dependency detected: repositories.modelARepository --> @modelARepository.constructor[1] --> repositories.modelBRepository --> @modelBRepository.constructor[1] --> repositories.modelARepository

What should I do to be able to call modelBs from modelA AND modelA from modelB?

### Reproduction

not needed

**Comment by samarpanB** [comment] 2022-11-08 12:23
Can you please share an example repo where it can be reproduced ? I am asking because we use it in many places and have never encountered this error in such cases. hasmany and belongsto are meant to work always in tandem and circular dependency is handled in relations code.

**Comment by taoyuan** [comment] 2022-12-02 07:49
I ran into a similar problem, I committed a [test repo](https://github.com/taoyuan/lb-circular-test).

## Steps to reproduce

1. Clone [this repo](https://github.com/taoyuan/lb-circular-test)
2. Run `yarn`
3. Run `yarn test`

## Expected result

The test should pass.

## Actual result

The test fails with the following error:

```
 Error thrown from get /tasks => TaskController.find Error: Circular dependency detected: controllers.UserController --> @UserController.constructor[0] --> repositories.UserRepository --> @UserRepository.constructor[1] --> repositories.TaskRepository --> @TaskRepository.constructor[1] --> repositories.UserRepository
```

## Notes

The testing codes:

```ts
  it('invokes GET /query', async () => {
    await client.get('/users').expect(200); // This line passes
    await client.get('/tasks').expect(200); // This line fails
  });
```

- The error is thrown for the second rest call to `GET /tasks`
- The dependency chain seams confusing. Shouldn't the circular dependency path be from `controllers.TaskController`? Why is `controllers.UserController` involved?
- No error is thrown with `singletons: false` in repositories.
- No error is thrown with all repositories injected in `controllers.UserController` constructor.

> Can you please share an example repo where it can be reproduced ? I am asking because we use it in many places and have never encountered this error in such cases. hasmany and belongsto are meant to work always in tandem and circular dependency is handled in relations code.

**Comment by samarpanB** [comment] 2022-12-02 09:41
Found the issue. You need to make repositories Transient. Then it will work. With singleton repositories, it causes same references to be used and hence cyclic deps error. I just tried on your repo and it worked. See this PR -> https://github.com/taoyuan/lb-circular-test/pull/1/files

**Comment by taoyuan** [comment] 2022-12-03 08:37
Thank you very much for your reply.

I know use transient to circumvent the problem, but I wonder if this problem is normal in singleton mode.

For performance reasons, I prefer to make the repository use singletons as much as possible. At present, my approach is to initialize all singleton objects that may have problems when initializing the project, so as to avoid circular dependency problems. But I don't think this should be the norm.

**Comment by raymondfeng** [comment] 2022-12-03 16:32
Did u try https://loopback.io/doc/en/lb4/Decorators_inject.html#injectgetter?

**Comment by taoyuan** [comment] 2022-12-04 08:03
@raymondfeng Do you mean inject respository with getter in controller? 

I committed a [branch](https://github.com/taoyuan/lb-circular-test/tree/repository-getter) to inject repository with getter in controller and got the same error.

```
Request GET /tasks failed with status code 500. Error: Circular dependency detected: controllers.UserController --> @UserController.constructor[0] --> repositories.UserRepository --> @UserRepository.constructor[1] --> repositories.TaskRepository --> @TaskRepository.constructor[1] --> repositories.UserRepository
```

**Comment by raymondfeng** [comment] 2022-12-04 16:26
The following test works for me:
```ts
  it('allows circular dependencies of two lazy bindings', async () => {
    const context = new Context();
    interface XInterface {
      value: string;
      yVal(): Promise<string>;
    }
    interface YInterface {
      value: string;
    }

    class XClass implements XInterface {
      value = 'x';
      @inject.getter('y')
      public y: Getter<YInterface>;

      async yVal() {
        const y = await this.y();
        return y.value;
      }
    }

    class YClass implements YInterface {
      value = 'y';
      @inject.getter('x')
      public x: Getter<XInterface>;
    }

    context.bind('x').toClass(XClass);
    context.bind('y').toClass(YClass);

    const x = context.getSync<XInterface>('x');
    const y = await x.yVal();
    expect(y).to.eql('y');
  });
  ```

**Comment by raymondfeng** [comment] 2022-12-04 18:56
An interesting bug. I created #9130 to fix it.

**Closed** 2022-12-05 18:37 UTC
Labels: bug
